version: '3.6'

services:
  server:
    container_name: dev-gorlami-server
    image: dev-gorlami-server
    ports:
      - 9001:9001
    volumes:
      - ./:/go/src/redanthrax/gorlami-server
    build:
      dockerfile: dev.Dockerfile
  nats:
    container_name: dev-nats-server
    image: nats:latest
    ports:
      - 4222:4222