version: '3.6'

services:
  server:
    container_name: gorlami-server
    image: gorlami-server
    ports:
      - 3000:3000
    volumes:
      - ./:/go/src/redanthrax/gorlami-server
    build:
      dockerfile: Dockerfile