version: '3'
tasks:
  run:
    cmds:
      - 'go build . -o server && ./server'
  css:
    cmds:
      - 'cd frontend && postcss static/main.css -o static/compiled.css'
  dockerdev:
    cmds:
      - 'docker compose -f dev.docker-compose.yml up'