version: '3'

tasks:
  run:
    cmds:
      - go build
      - gorlami.exe
  build:
    cmds:
      - go build
      - '{{if eq OS "windows"}}powershell Copy-Item -Path gorlami.exe -Destination "C:\agent\gorlami.exe"{{end}}'
    silent: true